// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderJournal struct {
	CommandID   string             `db:"command_id" json:"command_id"`
	Ticker      string             `db:"ticker" json:"ticker"`
	Sequence    int64              `db:"sequence" json:"sequence"`
	CommandType string             `db:"command_type" json:"command_type"`
	Payload     []byte             `db:"payload" json:"payload"`
	RecordedAt  pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type OrderJournalSequence struct {
	Ticker       string `db:"ticker" json:"ticker"`
	LastSequence int64  `db:"last_sequence" json:"last_sequence"`
}
