// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_journal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderJournalEntry = `-- name: CreateOrderJournalEntry :one
WITH next_sequence AS (
    INSERT INTO order_journal_sequences (ticker, last_sequence)
    VALUES ($2, 1)
    ON CONFLICT (ticker) DO UPDATE
    SET last_sequence = order_journal_sequences.last_sequence + 1
    RETURNING last_sequence
)
INSERT INTO order_journal (
    command_id,
    ticker,
    sequence,
    command_type,
    payload
)
SELECT $1, $2, last_sequence, $3, $4
FROM next_sequence
ON CONFLICT (command_id) DO NOTHING
RETURNING sequence, recorded_at
`

type CreateOrderJournalEntryParams struct {
	CommandID   string `db:"command_id" json:"command_id"`
	Ticker      string `db:"ticker" json:"ticker"`
	CommandType string `db:"command_type" json:"command_type"`
	Payload     []byte `db:"payload" json:"payload"`
}

type CreateOrderJournalEntryRow struct {
	Sequence   int64              `db:"sequence" json:"sequence"`
	RecordedAt pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

func (q *Queries) CreateOrderJournalEntry(ctx context.Context, arg CreateOrderJournalEntryParams) (CreateOrderJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, createOrderJournalEntry,
		arg.CommandID,
		arg.Ticker,
		arg.CommandType,
		arg.Payload,
	)
	var i CreateOrderJournalEntryRow
	err := row.Scan(&i.Sequence, &i.RecordedAt)
	return i, err
}

const getOrderJournalEntry = `-- name: GetOrderJournalEntry :one
SELECT command_id, ticker, sequence, command_type, payload, recorded_at
FROM order_journal
WHERE command_id = $1
`

func (q *Queries) GetOrderJournalEntry(ctx context.Context, commandID string) (OrderJournal, error) {
	row := q.db.QueryRow(ctx, getOrderJournalEntry, commandID)
	var i OrderJournal
	err := row.Scan(
		&i.CommandID,
		&i.Ticker,
		&i.Sequence,
		&i.CommandType,
		&i.Payload,
		&i.RecordedAt,
	)
	return i, err
}

const listOrderJournalEntries = `-- name: ListOrderJournalEntries :many
SELECT command_id, ticker, sequence, command_type, payload, recorded_at
FROM order_journal
ORDER BY ticker, sequence
`

func (q *Queries) ListOrderJournalEntries(ctx context.Context) ([]OrderJournal, error) {
	rows, err := q.db.Query(ctx, listOrderJournalEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderJournal
	for rows.Next() {
		var i OrderJournal
		if err := rows.Scan(
			&i.CommandID,
			&i.Ticker,
			&i.Sequence,
			&i.CommandType,
			&i.Payload,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
